### PR TITLE
Contribution

### PR DESCRIPTION
**Pull request by methlox**
Added contribution guidelines and a PR template. Will implement proposed changes!

### CODE REVIEW

**Comment by dhruvsol** [comment]
@methlox  whenever you're done put me for review 
Thanks

**Comment by methlox** [comment]
@dhruvsol there shouldn't be anymore changes. Fixed typos and hyperlinks. Check once and suggest changes

**Comment by dhruvsol** [comment]
@methlox  can you make `contribution.md` for all the repo inside apps and link it to the main one? because the current one is just instructions to run the main repo. might cause confusion. what do you think ?

**Comment by methlox** [comment]
@dhruvsol I can do it if you see it fit. Never seen this one before tho. Usually, devs clone the main repo, make changes to whatever section and push the entire repo. I might be wrong

**Pull request closed without merging**
