### PR TITLE
Dashboard project datafetch

### PR DESCRIPTION
**Pull request by Dank-del**

### CODE REVIEW

**Comment by Dank-del** [comment]
Screenshot 2024-01-06 at 1 20 00 AM
Would like if someone made the drawer work sideways 
[Issue on vaul repo](https://github.com/emilkowalski/vaul/pull/187)

**Comment by irffanasiff** [comment]
@Dank-del you can use radix drawer/portal/modal or anything to make this behaviour and make a side drawer component or check how shadcn does it

**Comment by Dank-del** [comment]
Screenshot 2024-01-06 at 3 12 16 PM

**Comment by irffanasiff** [comment]
do styles/css properly or i wont merge 👹

**Pull request merged**
